### PR TITLE
Clean up display of test cases

### PR DESCRIPTION
**Pull request by alexthemark**
Cleans up how system tests are displayed. They now look somewhat nicer like JUnit. 

@Aalk4308, I've modified test.bat in a way I think should work in the Windows .bat file, but please test.

### CODE REVIEW

**Comment by akallem** [comment]
This is great, I'm good with this.

**Comment by alexthemark** [comment]
I made it so the shell script will only print the file name instead of the path... Unfortunately I don't know how to do this in batch.

**Comment by mzbenami** [comment]
looks good to me, thanks guys.

**Comment by akallem** [comment]
I'll see if I can have it omit the path in the Windows batch script.

**Comment by akallem** [comment]
OK, I think this is good to go now.

**Pull request merged**
