### PR TITLE
Restrict Class and Listener Creation

### LINKED ISSUE #78: Restrict Statements in Blocks
Change grammar to restrict the kinds of statements that can appear inside blocks like custom action definitions, listeners, etc.

### PR DESCRIPTION
**Pull request by akallem**
This branch updates the grammar to prevent class and listener declarations from occurring within blocks.  Essentially, I just made a distinction between what I called declarative statements (class and listener creation) versus non-declarative statements.  Blocks can only contain a list of non-declarative statements.

FYI, I've also updated the reference manual chapter in our final report to reflect this.

Closes #78

### CODE REVIEW

**Comment by mzbenami** [comment]
i like i

**Comment by mzbenami** [comment]
t

**Comment by alexthemark** [comment]
Looks good

**Comment by akallem** [comment]
@ZhangWangda @jtyoung1292 since this is a simple one, take a quick look and leave a comment here, then I'll merge it.

**Pull request merged**
