### PR TITLE
System Test Refactor

### PR DESCRIPTION
**Pull request by akallem**
This branch renames the system test programs and log files to use a consistent naming, and it reduces the log files length from 500 to just 100.

(It also incorporates the flip y-axis branch.)

### CODE REVIEW

**Comment by akallem** [comment]
@alexthemark @mzbenami @ZhangWangda @jtyoung1292 to make sure any future system tests we write are consistent with this, it would be great it you could review this soon so we can merge it soon (if you agree it makes sense).

**Comment by alexthemark** [comment]
As I said in the meeting, I'd prefer to do this but also have an option

**Comment by alexthemark** [comment]
Oops, accidentally closed and reopened... never mind that.

I'm good with this change. I thought more about my idea of having max frames be an argument into Words, and that would be really annoying since we've automated all of our tests and haven't provided a good location where we could include that argument. 100 frames seems reasonable.

**Comment by zwdnyc** [comment]
looks nice

**Comment by akallem** [comment]
Thanks, glad you thought about it more, because that was exactly going to be my response.  :-)

**Pull request merged**
