### PR TITLE
Refactor packages

### PR DESCRIPTION
**Pull request by alexthemark**
Organize the code base into various packages, since it was very large. 

Test cases work now. There are no real changes to code except for the now-necessary import statements. Since we're no longer using the default package for everything, it is sometimes necessary to import various parts of our code (i.e. exceptions), but this seems normal for most Java code bases.

### CODE REVIEW

**Comment by akallem** [comment]
This looks great, I'm good with this.

**Comment by alexthemark** [comment]
I think we should probably merge mine and Wangda's branches tonight so that Michael and James can incorporate them for their Friday update. @mzbenami @jtyoung1292 it would be great if you had time to look over these tonight so that we can merge.

**Comment by mzbenami** [comment]
looks good, thanks.

**Comment by youngthejames** [comment]
looks good.

**Pull request merged**
