### PR TITLE
Test INodeQueueSay

### LINKED ISSUE #37: Test evalQueueSay
Using JUnit

### PR DESCRIPTION
**Pull request by zwdnyc**
resolve #37

### CODE REVIEW

**Comment by akallem** [comment]
This looks good.  The one thing I'd suggest adding is a test that the right exception is thrown when we try to have an object say something that is not a string or number.  But I suppose that test could either be here or in the WordsSay class.

**Comment by mzbenami** [comment]
lgtm

**Comment by zwdnyc** [comment]
Added a test for expected WordsInvalidTypeException when an object says something other than a string or a number.

**Comment by akallem** [comment]
This looks good to me now.

**Pull request merged**
