### PR TITLE
Documentation

### LINKED ISSUE #140: Documentation on Github
Move documentation from Google Drive to Github.

### PR DESCRIPTION
**Pull request by alexthemark**
Places our whitepaper as a markdown README that first appears when you enter the repo. LRM and Tutorial then exist in the documentation folder. I included LRM and Tutorial but not final report as the LRM and Tutorial are supporting documentation for this repository, but the report is very much "We are students this is class" material. 

LRM and Tutorial are PDFs because the Markdown conversion process isn't perfect and it would have been very time consuming to fix. The whitepaper is markdown so that you can see it immediately upon opening the repo. 

Closes #140

### CODE REVIEW

**Comment by mzbenami** [comment]
kid never stops grindin, we have a NLP final tomorrow!

**Comment by mzbenami** [comment]
lgtm

**Comment by alexthemark** [comment]
How do you think I procrastinate

**Comment by akallem** [comment]
Looks good to me!

**Pull request merged**
